python main.py --model=cevt --cutoff_dataset=0 --hidden_dim=128 --optim=adam --lr_init=1e-2 --wd=1e-2 --epochs=300 --scheduler=cos_anneal --t_max=300 --drop_out=0.1 --num_layers=1 --cet_transformer_layers=5 --num_features=64 --num_heads=4 --lambdas 1 1e-1 1e-6 --run_group=cutoffs_double_treat --sig_x0=0.75 --residual_x --use_treatment --MC_sample=1 --ignore_wandb
python main.py --model=transformer --hidden_dim=128 --optim=adam --lr_init=1e-2 --wd=1e-4 --epochs=200 --scheduler=cos_anneal --t_max=200 --drop_out=0.0 --num_layers=2 --num_heads=8 --run_group=baselines_double_treatment_only0 --seed=1000 --cutoff_dataset=0 --ignore_wandb
python main.py --model=mlp --hidden_dim=128 --optim=adam --lr_init=1e-3 --wd=1e-3 --epochs=200 --scheduler=cos_anneal --t_max=200 --drop_out=0.1 --num_layers=2 --num_features=128 --run_group=baselines_double_treatment_only0 --seed=1000 --cutoff_dataset=0 --ignore_wandb
python main.py --model=cevae --cutoff_dataset=0 --hidden_dim=128 --optim=adam --lr_init=1e-2 --wd=1e-4 --epochs=300 --scheduler=cos_anneal --t_max=300 --drop_out=0.1 --num_layers=3 --cet_transformer_layers=4 --num_features=128 --lambdas 1 1e-6 1e-6 --run_group=cevae --use_treatment --single_treatment --MC_sample=1 --ignore_wandb
python main.py --model=linear --hidden_dim=128 --optim=adam --lr_init=1e-4 --wd=1e-3 --epochs=200 --scheduler=cos_anneal --t_max=200 --drop_out=0.1 --num_layers=2 --num_features=128 --run_group=baselines_double_treatment_only0 --seed=1000 --cutoff_dataset=0 --ignore_wandb
python main.py --model=ridge --hidden_dim=256 --optim=adam --lr_init=1e-2 --wd=1e-4 --epochs=200 --scheduler=cos_anneal --t_max=200 --drop_out=0.1 --num_layers=3 --num_features=256 --lamb=10 --run_group=baselines_double_treatment_only0 --seed=1000 --cutoff_dataset=0 --ignore_wandb
python run_causal.py --model=dragonnet --use_treatment --single_treatment --run_group=dragonnet --lr_init=1e-3 --optim=adam --wd=1e-4 --alpha=10 --epochs=200 --ignore_wandb
python run_causal.py --model=tarnet --use_treatment --single_treatment --run_group=tarnet --lr_init=1e-3 --optim=adam --wd=1e-3 --alpha=1 --epochs=200 --ignore_wandb
python run_itransformer.py --model=iTransformer --use_treatment --single_treatment --run_group=itransformer --hidden_dim=128 --num_layers=3 --num_heads=8 --lr_init=1e-3 --optim=adam --wd=1e-4 --drop_out=0.0 --epochs=200 --ignore_wandb
