python main.py --model=linear --cutoff_dataset=0 --hidden_dim=256 --optim=adam --lr_init=1e-4 --is_municipal --wd=1e-1 --epochs=50 --scheduler=cos_anneal --t_max=50  --drop_out=0.2 --num_layers=2 --municipal_max_cluster=98 --num_features=64
python main.py --model=ridge --cutoff_dataset=0 --hidden_dim=64 --optim=adam --lr_init=1e-4 --wd=1e-1 --epochs=50 --scheduler=cos_anneal --is_municipal --t_max=50  --drop_out=0 --num_layers=3 --num_features=64 --lamb=10 --municipal_max_cluster=98
python main.py --model=mlp --cutoff_dataset=0 --is_municipal --hidden_dim=256 --optim=adam --lr_init=1e-3 --wd=1e-1 --epochs=50 --scheduler=cos_anneal  --t_max=50 --drop_out=0 --num_layers=2 --municipal_max_cluster=98 --num_features=64
python main.py --model=cevae --cutoff_dataset=0 --hidden_dim=64 --optim=adam --lr_init=1e-2 --wd=1e-3  --epochs=50 --scheduler=cos_anneal --is_municipal --t_max=50 --drop_out=0 --num_layers=3 --cevt_transformer_layers=4 --num_features=64 --lambdas 1 1e-6 1e-6 --use_treatment --single_treatment --municipal_max_cluster=98 --MC_sample=1
python main.py --model=transformer --cutoff_dataset=0 --hidden_dim=64 --optim=adam --lr_init=1e-2 --wd=1e-1 --is_municipal --epochs=50 --scheduler=cos_anneal --t_max=50  --drop_out=0 --num_layers=2 --municipal_max_cluster=98 --num_heads=8
python run_itransformer.py --model=iTransformer --use_treatment  --single_treatment --hidden_dim=128 --num_layers=2 --num_heads=8 --lr_init=1e-3 --is_municipal --optim=adam --wd=1e-3 --drop_out=0.2 --municipal_max_cluster=98 --epochs=50
python run_causal.py --model=dragonnet --use_treatment --single_treatment --epochs=50 --alpha=10  --lr_init=1e-2 --optim=adam --is_municipal --municipal_max_cluster=98 --wd=1e-2 --hidden_dim=128
python run_causal.py --model=tarnet --use_treatment --single_treatment --epochs=50  --alpha=1 --is_municipal --lr_init=1e-4 --optim=adam --wd=1e-1 --hidden_dim=256 --municipal_max_cluster=98
python main.py --model=cevt --cutoff_dataset=0 --hidden_dim=128 --optim=adam --lr_init=1e-2 --wd=1e-3 --epochs=50 --scheduler=cos_anneal --t_max=50 --drop_out=0.2 --num_layers=1 --cevt_transformer_layers=5 --num_features=64 --num_heads=8 --is_municipal --variational --lambdas 1 1e-1 1e-6 --sig_x0=0.75 --use_treatment --MC_sample=1 --lagging_num=1  --municipal_max_cluster=98
